In [8]:
'''EGLINTON AND EDEN VALLEY 2015 COUNTS'''

import pandas as pd

#I deleted empty rows within the tables before uploading this file
# I changed 'west' and 'east' to 'WB' and 'EB' before uploading this file

'''load excel file for parsing'''
xl = pd.ExcelFile('Eglinton & Eden Valley.xls')
nrows = xl.book.sheet_by_index(0).nrows

'''parse tables into seperate dataframes to remove empty rows'''
df1 = xl.parse(0, skiprows = 3, skip_footer = nrows-33).dropna(axis=1, how='all')
df2 = xl.parse(0, skiprows = 42, skip_footer = nrows-72).dropna(axis=1, how='all')
df3 = xl.parse(0, skiprows = 81, skip_footer = nrows - 111 ).dropna(axis = 1, how = 'all')
df4 = xl.parse(0, skiprows = 119, skip_footer = nrows - 149 ).dropna(axis = 1, how = 'all')

'''reorganize df1'''
df1 = df1.set_index(['Unnamed: 1'])
df1 = df1.drop(['Unnamed: 6', 'Unnamed: 11'], axis = 1)
df1 = df1.T
df1 = df1.fillna(method = 'ffill')
df1 = df1.set_index(['Date:'])

'''reorganize df2'''
df2 = df2.set_index(['Unnamed: 1'])
df2 = df2.drop(['Unnamed: 6', 'Unnamed: 11'], axis = 1)
df2 = df2.T
df2 = df2.fillna(method = 'ffill')
df2 = df2.set_index(['Date:'])

'''reorganize df3'''
df3 = df3.set_index(['Unnamed: 1'])
df3 = df3.drop(['Unnamed: 6', 'Unnamed: 11'], axis = 1)
df3 = df3.T
df3 = df3.fillna(method = 'ffill')
df3 = df3.set_index(['Date:'])

'''reorganize df4'''
df4 = df4.set_index(['Unnamed: 1'])
df4 = df4.T
df4 = df4.fillna(method = 'ffill')
df4 = df4.set_index(['Date:'])

'''recombine into 1 dataframe'''
eglinton_edenvalley2015_df = pd.concat([df1, df2, df3, df4])

'''add intersection column'''
eglinton_edenvalley2015_df['Intersection'] = 'Eglinton and Eden Valley'

'''rename columns/index for consistency'''
eglinton_edenvalley2015_df = eglinton_edenvalley2015_df.rename(columns = {'Day:':'Day','Weather:':'Weather','Hour':'Direction'})
eglinton_edenvalley2015_df.index.name = 'Date'

'''check final result'''
eglinton_edenvalley2015_df

Unnamed: 1,Day,Weather,Direction,00:00:00,01:00:00,02:00:00,03:00:00,04:00:00,05:00:00,06:00:00,...,16:00:00,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00,Totals,Intersection
Date,,,,,,,,,,,,,,,,,,,,,
2015-07-17,Friday,"21°C, 5mm rain",EB,1,0,0,0,0,1,3,...,11,8,6,6,1,1,2,0,60,Eglinton and Eden Valley
2015-07-17,Friday,"21°C, 5mm rain",WB,1,0,0,0,0,0,5,...,1,0,3,2,1,4,0,1,40,Eglinton and Eden Valley
2015-07-17,Friday,"21°C, 5mm rain",Total,2,0,0,0,0,1,8,...,12,8,9,8,2,5,2,1,100,Eglinton and Eden Valley
2015-07-18,Saturday,"29°C, no rain",EB,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,14,Eglinton and Eden Valley
2015-07-18,Saturday,"29°C, no rain",WB,0,0,0,0,0,0,0,...,4,2,2,0,0,1,0,0,14,Eglinton and Eden Valley
2015-07-18,Saturday,"29°C, no rain",Total,0,0,0,0,0,0,0,...,5,2,2,0,0,2,0,0,28,Eglinton and Eden Valley
2015-07-19,Sunday,"30°C, no rain",EB,0,0,0,0,0,0,0,...,1,1,5,1,4,1,1,0,44,Eglinton and Eden Valley
2015-07-19,Sunday,"30°C, no rain",WB,0,1,0,0,0,0,0,...,0,3,3,1,3,0,2,0,32,Eglinton and Eden Valley
2015-07-19,Sunday,"30°C, no rain",Total,0,1,0,0,0,0,0,...,1,4,8,2,7,1,3,0,76,Eglinton and Eden Valley
2015-07-20,Monday,"28°C, no rain",EB,0,0,0,0,0,0,3,...,5,26,26,25,11,10,0,2,137,Eglinton and Eden Valley
2015-07-20,Monday,"28°C, no rain",WB,0,0,0,0,0,0,3,...,5,11,13,4,13,2,2,1,80,Eglinton and Eden Valley
2015-07-20,Monday,"28°C, no rain",Total,0,0,0,0,0,0,6,...,10,37,39,29,24,12,2,3,217,Eglinton and Eden Valley
2015-07-21,Tuesday,"27°C, no rain",EB,1,0,0,0,0,0,6,...,25,29,29,17,36,12,1,0,228,Eglinton and Eden Valley
2015-07-21,Tuesday,"27°C, no rain",WB,0,0,0,0,0,1,11,...,10,17,10,11,23,5,1,3,169,Eglinton and Eden Valley
2015-07-21,Tuesday,"27°C, no rain",Total,1,0,0,0,0,1,17,...,35,46,39,28,59,17,2,3,397,Eglinton and Eden Valley
2015-07-22,Wednesday,"26°C, no rain",EB,1,0,1,0,0,0,6,...,20,35,27,10,13,4,2,1,182,Eglinton and Eden Valley
2015-07-22,Wednesday,"26°C, no rain",WB,1,0,0,0,0,1,7,...,7,10,10,7,7,4,0,1,135,Eglinton and Eden Valley
2015-07-22,Wednesday,"26°C, no rain",Total,2,0,1,0,0,1,13,...,27,45,37,17,20,8,2,2,317,Eglinton and Eden Valley
2015-07-23,Thursday,"27°C, no rain",EB,2,1,1,0,0,1,5,...,20,25,27,24,16,2,3,0,198,Eglinton and Eden Valley
2015-07-23,Thursday,"27°C, no rain",WB,1,0,0,0,1,2,7,...,8,15,4,12,11,9,6,2,162,Eglinton and Eden Valley
2015-07-23,Thursday,"27°C, no rain",Total,3,1,1,0,1,3,12,...,28,40,31,36,27,11,9,2,360,Eglinton and Eden Valley
2015-07-24,Friday,"28°C, no rain",EB,1,0,0,0,0,1,5,...,14,21,12,10,11,7,4,2,159,Eglinton and Eden Valley
2015-07-24,Friday,"28°C, no rain",WB,0,0,0,0,0,0,6,...,5,9,8,14,8,1,5,3,135,Eglinton and Eden Valley
2015-07-24,Friday,"28°C, no rain",Total,1,0,0,0,0,1,11,...,19,30,20,24,19,8,9,5,294,Eglinton and Eden Valley
2015-07-25,Saturday,"29°C, no rain",EB,0,0,0,0,0,0,3,...,10,5,7,4,9,9,0,1,171,Eglinton and Eden Valley
2015-07-25,Saturday,"29°C, no rain",WB,1,0,0,0,0,0,2,...,8,6,6,6,8,9,0,1,139,Eglinton and Eden Valley
2015-07-25,Saturday,"29°C, no rain",Total,1,0,0,0,0,0,5,...,18,11,13,10,17,18,0,2,310,Eglinton and Eden Valley
2015-07-26,Sunday,"30°C, no rain",EB,0,0,0,0,0,2,4,...,5,11,12,6,9,4,1,1,207,Eglinton and Eden Valley
2015-07-26,Sunday,"30°C, no rain",WB,0,0,0,0,0,0,0,...,11,10,1,14,4,5,2,1,162,Eglinton and Eden Valley
2015-07-26,Sunday,"30°C, no rain",Total,0,0,0,0,0,2,4,...,16,21,13,20,13,9,3,2,369,Eglinton and Eden Valley

In [9]:
'''ADELAIDE AND SPADINA 2015 COUNTS'''

import pandas as pd

#It was noted in the spreadsheet that this is a one-way eastbound bike lane

xl = pd.ExcelFile('Adelaide & Spadina 2015.xlsx')
nrows = xl.book.sheet_by_index(0).nrows

df1 = xl.parse(0, skiprows = 3, skip_footer = nrows-32).dropna(axis=1, how='all')
df2 = xl.parse(0, skiprows = 36, skip_footer = nrows-65).dropna(axis=1, how='all')

df1 = df1.set_index(['Unnamed: 0'])
df1 = df1.T
df1 = df1.set_index(['Date'])

df2 = df2.set_index(['Unnamed: 0'])
df2 = df2.T
df2 = df2.set_index(['Date'])

adelaide_spadina2015_df = pd.concat([df1, df2])

adelaide_spadina2015_df['Direction'] = 'EB'
adelaide_spadina2015_df['Intersection'] = 'Adelaide and Spadina'

adelaide_spadina2015_df = adelaide_spadina2015_df.rename(columns = {'Total':'Totals'})

adelaide_spadina2015_df

Unnamed: 0,Day,Weather,00:00:00,01:00:00,02:00:00,03:00:00,04:00:00,05:00:00,06:00:00,07:00:00,...,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00,Totals,Direction,Intersection
Date,,,,,,,,,,,,,,,,,,,,,
2015-05-16,Saturday,"23°C, no rain",13,5,4,2,2,2,8,15,...,80,73,69,56,31,21,19,1012,EB,Adelaide and Spadina
2015-05-17,Sunday,"16°C, no rain",13,12,9,5,4,4,6,9,...,74,64,59,45,44,17,11,983,EB,Adelaide and Spadina
2015-05-18,Monday,"19°C, no rain",11,7,3,10,3,3,8,8,...,63,68,55,40,32,19,9,888,EB,Adelaide and Spadina
2015-05-19,Tuesday,"18°C, no rain",8,3,0,2,2,8,54,121,...,120,125,86,37,48,16,11,2286,EB,Adelaide and Spadina
2015-05-20,Wednesday,"15°C, no rain",8,2,0,1,6,3,41,109,...,122,143,89,53,42,26,16,2236,EB,Adelaide and Spadina
2015-05-21,Thursday,"18°C, no rain",11,5,3,0,2,11,54,107,...,145,124,96,67,58,25,25,2415,EB,Adelaide and Spadina
2015-05-22,Friday,"15°C, no rain",10,3,4,1,9,8,44,91,...,137,123,96,48,43,20,22,2266,EB,Adelaide and Spadina
2014-08-08,Friday,"25°C, no rain",17,9,6,2,4,3,6,18,...,81,84,72,45,30,26,29,1227,EB,Adelaide and Spadina
2014-08-09,Saturday,"26°C, no rain",18,13,8,8,5,3,5,16,...,98,66,68,39,38,25,21,1181,EB,Adelaide and Spadina

In [10]:
'''RICHMOND AND SPADINA 2015 COUNTS'''

import pandas as pd

#It was noted in the spreadsheet that this is a one-way westbound bike lane

xl = pd.ExcelFile('Richmond & Spadina 2015.xlsx')
nrows = xl.book.sheet_by_index(0).nrows

df1 = xl.parse(0, skiprows = 3, skip_footer = nrows-32).dropna(axis=1, how='all')
df2 = xl.parse(0, skiprows = 36, skip_footer = nrows-65).dropna(axis=1, how='all')

df1 = df1.set_index(['Unnamed: 0'])
df1 = df1.T
df1 = df1.set_index(['Date'])

df2 = df2.set_index(['Unnamed: 0'])
df2 = df2.T
df2 = df2.set_index(['Date'])

richmond_spadina2015_df = pd.concat([df1, df2])

richmond_spadina2015_df['Direction'] = 'WB'
richmond_spadina2015_df['Intersection'] = 'Richmond and Spadina'

richmond_spadina2015_df = richmond_spadina2015_df.rename(columns = {'Total':'Totals'})

richmond_spadina2015_df

Unnamed: 0,Day,Weather,00:00:00,01:00:00,02:00:00,03:00:00,04:00:00,05:00:00,06:00:00,07:00:00,...,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00,Totals,Direction,Intersection
Date,,,,,,,,,,,,,,,,,,,,,
2015-05-16,Saturday,"23°C, no rain",40,25,13,4,2,2,7,7,...,64,62,56,54,58,69,44,915,WB,Richmond and Spadina
2015-05-17,Sunday,"16°C, no rain",50,39,12,5,3,3,1,6,...,66,85,61,42,46,47,37,866,WB,Richmond and Spadina
2015-05-18,Monday,"19°C, no rain",47,25,4,6,5,2,1,2,...,82,67,57,50,43,34,65,799,WB,Richmond and Spadina
2015-05-19,Tuesday,"18°C, no rain",34,2,0,1,2,4,8,25,...,465,341,173,100,95,91,71,2163,WB,Richmond and Spadina
2015-05-20,Wednesday,"15°C, no rain",39,23,7,2,2,4,8,19,...,381,305,163,133,98,111,80,1987,WB,Richmond and Spadina
2015-05-21,Thursday,"18°C, no rain",33,11,3,2,2,2,9,32,...,433,309,192,128,104,117,74,2161,WB,Richmond and Spadina
2015-05-22,Friday,"15°C, no rain",10,3,4,1,9,8,44,91,...,137,123,96,48,43,20,22,2266,WB,Richmond and Spadina
2015-05-23,Saturday,"16°C, no rain",11,4,2,1,2,6,25,50,...,87,56,54,29,32,30,22,1349,WB,Richmond and Spadina
2015-05-24,Sunday,"23°C, no rain",51,52,15,12,5,3,2,10,...,106,108,82,59,59,49,36,1228,WB,Richmond and Spadina

In [11]:
'''SIMCOE AND ADELAIDE 2015 COUNTS'''

import pandas as pd

#note that I deleted empty rows within the tables before uploading this file 

xl = pd.ExcelFile('Simcoe & Adelaide.xls')
nrows = xl.book.sheet_by_index(0).nrows

df1 = xl.parse(0, skiprows = 3, skip_footer = nrows-33).dropna(axis=1, how='all')
df2 = xl.parse(0, skiprows=42, skip_footer = nrows - 72).dropna(axis=1, how='all')
df3 = xl.parse(0, skiprows = 81, skip_footer = nrows-111).dropna(axis=1, how='all')

df1 = df1.set_index(['Unnamed: 1'])
df1 = df1.drop(['Unnamed: 6', 'Unnamed: 11'], axis = 1)
df1 = df1.T
df1 = df1.fillna(method = 'ffill')
df1 = df1.set_index(['Date:'])

df2 = df2.set_index(['Unnamed: 1'])
df2 = df2.drop(['Unnamed: 6', 'Unnamed: 11'], axis = 1)
df2 = df2.T
df2 = df2.fillna(method = 'ffill')
df2 = df2.set_index(['Date:'])

df3 = df3.set_index(['Unnamed: 1'])
df3 = df3.drop(['Unnamed: 6', 'Unnamed: 11'], axis = 1)
df3 = df3.T
df3 = df3.fillna(method = 'ffill')
df3 = df3.set_index(['Date:'])

simcoe_adelaide2015_df = pd.concat([df1, df2, df3])

simcoe_adelaide2015_df['Intersection'] = 'Simcoe and Adelaide'
simcoe_adelaide2015_df = simcoe_adelaide2015_df.rename(columns={'Day:':'Day', 'Weather:':'Weather', 'Hour':'Direction'})
simcoe_adelaide2015_df.index.name = 'Date'


simcoe_adelaide2015_df

Unnamed: 1,Day,Weather,Direction,00:00:00,01:00:00,02:00:00,03:00:00,04:00:00,05:00:00,06:00:00,...,16:00:00,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00,Totals,Intersection
Date,,,,,,,,,,,,,,,,,,,,,
2015-05-27,Wednesday,"25°C, no rain",NB,11,1,2,1,3,4,11,...,94,156,84,37,38,29,29,18,885,Simcoe and Adelaide
2015-05-27,Wednesday,"25°C, no rain",SB,2,3,0,1,2,6,22,...,53,67,43,40,24,21,18,7,898,Simcoe and Adelaide
2015-05-27,Wednesday,"25°C, no rain",Total,13,4,2,2,5,10,33,...,147,223,127,77,62,50,47,25,1783,Simcoe and Adelaide
2015-05-28,Thursday,"26°C, no rain",NB,10,4,1,2,0,6,11,...,107,159,84,62,36,34,45,25,982,Simcoe and Adelaide
2015-05-28,Thursday,"26°C, no rain",SB,1,5,0,0,2,2,20,...,66,91,69,51,22,24,17,10,1083,Simcoe and Adelaide
2015-05-28,Thursday,"26°C, no rain",Total,11,9,1,2,2,8,31,...,173,250,153,113,58,58,62,35,2065,Simcoe and Adelaide
2015-05-29,Friday,"24°C, no rain",NB,6,6,2,3,1,1,11,...,107,167,86,43,25,31,23,26,915,Simcoe and Adelaide
2015-05-29,Friday,"24°C, no rain",SB,10,2,1,1,1,8,25,...,75,66,44,41,26,26,8,7,1023,Simcoe and Adelaide
2015-05-29,Friday,"24°C, no rain",Total,16,8,3,4,2,9,36,...,182,233,130,84,51,57,31,33,1938,Simcoe and Adelaide
2015-05-30,Saturday,"28°C, 22mm rain",NB,16,8,2,2,5,0,6,...,25,18,8,15,17,9,11,9,357,Simcoe and Adelaide
2015-05-30,Saturday,"28°C, 22mm rain",SB,9,2,0,1,0,2,10,...,10,7,18,16,14,2,3,4,345,Simcoe and Adelaide
2015-05-30,Saturday,"28°C, 22mm rain",Total,25,10,2,3,5,2,16,...,35,25,26,31,31,11,14,13,702,Simcoe and Adelaide
2015-05-31,Sunday,"12°C, 20mm rain",NB,8,5,7,1,0,0,2,...,8,10,12,3,6,5,7,4,148,Simcoe and Adelaide
2015-05-31,Sunday,"12°C, 20mm rain",SB,0,2,0,1,0,4,7,...,4,7,6,3,3,3,3,1,105,Simcoe and Adelaide
2015-05-31,Sunday,"12°C, 20mm rain",Total,8,7,7,2,0,4,9,...,12,17,18,6,9,8,10,5,253,Simcoe and Adelaide
2015-06-01,Monday,"15°C, no rain",NB,1,1,1,0,0,0,7,...,80,143,79,52,37,28,13,7,775,Simcoe and Adelaide
2015-06-01,Monday,"15°C, no rain",SB,1,1,0,0,1,2,24,...,56,65,48,33,19,8,11,9,799,Simcoe and Adelaide
2015-06-01,Monday,"15°C, no rain",Total,2,2,1,0,1,2,31,...,136,208,127,85,56,36,24,16,1574,Simcoe and Adelaide
2015-06-02,Tuesday,"18°C, no rain",NB,7,4,0,3,0,4,12,...,92,164,128,54,52,35,26,26,1040,Simcoe and Adelaide
2015-06-02,Tuesday,"18°C, no rain",SB,6,1,2,1,1,3,24,...,78,87,57,35,21,24,13,5,1049,Simcoe and Adelaide
2015-06-02,Tuesday,"18°C, no rain",Total,13,5,2,4,1,7,36,...,170,251,185,89,73,59,39,31,2089,Simcoe and Adelaide
2015-06-03,Wednesday,"18°C, no rain",NB,7,3,3,2,0,3,8,...,109,186,109,39,53,47,34,23,1058,Simcoe and Adelaide
2015-06-03,Wednesday,"18°C, no rain",SB,8,2,1,0,1,3,29,...,67,85,57,46,30,19,13,3,1115,Simcoe and Adelaide
2015-06-03,Wednesday,"18°C, no rain",Total,15,5,4,2,1,6,37,...,176,271,166,85,83,66,47,26,2173,Simcoe and Adelaide
2015-06-04,Thursday,"22°C, no rain",NB,12,7,5,4,1,1,16,...,113,183,91,60,36,22,24,28,1017,Simcoe and Adelaide
2015-06-04,Thursday,"22°C, no rain",SB,0,2,0,1,3,7,29,...,84,80,62,42,23,17,20,8,1104,Simcoe and Adelaide
2015-06-04,Thursday,"22°C, no rain",Total,12,9,5,5,4,8,45,...,197,263,153,102,59,39,44,36,2121,Simcoe and Adelaide

In [17]:
'''WELLESLEY AND PARLIAMENT 2015 COUNTS'''

import pandas as pd

#prior to importing the file, I removed empty rows in the tables

xl = pd.ExcelFile('Wellesley & Parliament.xls')
nrows = xl.book.sheet_by_index(0).nrows

df1 = xl.parse(0, skiprows = 2, skip_footer = nrows-33).dropna(axis=1, how='all')
df2 = xl.parse(0, skiprows=36, skip_footer = nrows-67).dropna(axis=1, how='all')
df3 = xl.parse(0, skiprows = 69, skip_footer = nrows - 100 ).dropna(axis = 1, how = 'all')

df1 = df1.set_index(['Unnamed: 1'])
df1 = df1.drop(['Unnamed: 5', 'Unnamed: 9'], axis = 1)
df1 = df1.T
df1 = df1.fillna(method = 'ffill')
df1 = df1.set_index(['Date:'])

df2 = df2.set_index(['Unnamed: 1'])
df2 = df2.drop(['Unnamed: 5', 'Unnamed: 9'], axis = 1)
df2 = df2.T
df2 = df2.fillna(method = 'ffill')
df2 = df2.set_index(['Date:'])

df3 = df3.set_index(['Unnamed: 1'])
df3 = df3.drop(['Unnamed: 5', 'Unnamed: 9'], axis = 1)
df3 = df3.T
df3 = df3.fillna(method = 'ffill')
df3 = df3.set_index(['Date:'])

wellesley_parliament2015_df = pd.concat([df1, df2, df3]) 

wellesley_parliament2015_df['Intersection'] = 'Wellesley and Parliament'
wellesley_parliament2015_df = wellesley_parliament2015_df.drop(['Total'], axis = 1)
wellesley_parliament2015_df = wellesley_parliament2015_df.rename(columns={'Day:':'Day', 'Weather:':'Weather', 'Hour':'Direction',
                                                                         'Subtotal': 'Totals'})
wellesley_parliament2015_df.index.name = 'Date'

wellesley_parliament2015_df

Unnamed: 1,Day,Weather,Direction,00:00:00,01:00:00,02:00:00,03:00:00,04:00:00,05:00:00,06:00:00,...,16:00:00,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00,Totals,Intersection
Date,,,,,,,,,,,,,,,,,,,,,
2015-06-17,Wednesday,"21°C, no rain",EB,14,5,3,0,1,2,8,...,84,137,100,44,41,36,35,20,803,Wellesley and Parliament
2015-06-17,Wednesday,"21°C, no rain",WB,5,3,0,1,1,4,15,...,25,41,44,31,32,13,13,9,639,Wellesley and Parliament
2015-06-18,Thursday,"26°C, no rain",EB,9,6,2,1,3,6,6,...,74,97,83,56,38,31,28,12,745,Wellesley and Parliament
2015-06-18,Thursday,"26°C, no rain",WB,6,6,0,0,3,3,11,...,23,28,46,30,36,33,13,8,598,Wellesley and Parliament
2015-06-19,Friday,"20°C, no rain",EB,11,8,1,4,2,2,6,...,95,128,67,48,28,25,30,29,768,Wellesley and Parliament
2015-06-19,Friday,"20°C, no rain",WB,4,2,0,0,2,2,21,...,46,42,31,44,18,23,22,14,652,Wellesley and Parliament
2015-06-20,Saturday,"22°C, no rain",EB,16,10,3,2,1,5,5,...,55,38,52,38,21,30,27,12,609,Wellesley and Parliament
2015-06-20,Saturday,"22°C, no rain",WB,13,8,2,4,1,0,2,...,41,42,37,26,29,15,9,19,506,Wellesley and Parliament
2015-06-21,Sunday,"28°C, no rain",EB,23,17,11,3,1,7,1,...,39,37,29,33,25,24,14,13,520,Wellesley and Parliament
2015-06-21,Sunday,"28°C, no rain",WB,8,11,1,2,4,3,1,...,26,40,33,20,20,22,19,8,429,Wellesley and Parliament
2015-06-22,Monday,"27°C, 21mm rain",EB,9,4,7,8,0,2,5,...,96,146,85,64,34,21,20,8,720,Wellesley and Parliament
2015-06-22,Monday,"27°C, 21mm rain",WB,4,3,1,1,1,4,18,...,36,46,36,31,21,13,15,3,554,Wellesley and Parliament
2015-06-23,Tuesday,"27°C, 1mm rain",EB,4,3,0,1,0,2,3,...,82,106,88,52,42,40,22,19,713,Wellesley and Parliament
2015-06-23,Tuesday,"27°C, 1mm rain",WB,2,2,2,2,1,4,17,...,32,44,39,34,36,21,13,11,612,Wellesley and Parliament
2015-06-24,Wednesday,"25°C, no rain",EB,7,5,2,2,1,2,6,...,98,120,128,66,38,35,27,22,841,Wellesley and Parliament
2015-06-24,Wednesday,"25°C, no rain",WB,7,2,0,0,1,2,20,...,35,46,48,35,26,25,14,15,708,Wellesley and Parliament
2015-06-25,Thursday,"23°C, no rain",EB,7,6,3,3,2,4,10,...,64,107,86,52,38,27,21,21,707,Wellesley and Parliament
2015-06-25,Thursday,"23°C, no rain",WB,2,3,0,3,4,5,18,...,32,28,24,30,23,24,17,8,562,Wellesley and Parliament

In [20]:
'''Combine all into 2015 counts Dataframe'''

Bikecounts2015_df = pd.concat([adelaide_spadina2015_df, eglinton_edenvalley2015_df, richmond_spadina2015_df, simcoe_adelaide2015_df, wellesley_parliament2015_df])

Bikecounts2015_df

,Day,Weather,00:00:00,01:00:00,02:00:00,03:00:00,04:00:00,05:00:00,06:00:00,07:00:00,...,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00,Totals,Direction,Intersection
Date,,,,,,,,,,,,,,,,,,,,,
2015-05-16,Saturday,"23°C, no rain",13,5,4,2,2,2,8,15,...,80,73,69,56,31,21,19,1012,EB,Adelaide and Spadina
2015-05-17,Sunday,"16°C, no rain",13,12,9,5,4,4,6,9,...,74,64,59,45,44,17,11,983,EB,Adelaide and Spadina
2015-05-18,Monday,"19°C, no rain",11,7,3,10,3,3,8,8,...,63,68,55,40,32,19,9,888,EB,Adelaide and Spadina
2015-05-19,Tuesday,"18°C, no rain",8,3,0,2,2,8,54,121,...,120,125,86,37,48,16,11,2286,EB,Adelaide and Spadina
2015-05-20,Wednesday,"15°C, no rain",8,2,0,1,6,3,41,109,...,122,143,89,53,42,26,16,2236,EB,Adelaide and Spadina
2015-05-21,Thursday,"18°C, no rain",11,5,3,0,2,11,54,107,...,145,124,96,67,58,25,25,2415,EB,Adelaide and Spadina
2015-05-22,Friday,"15°C, no rain",10,3,4,1,9,8,44,91,...,137,123,96,48,43,20,22,2266,EB,Adelaide and Spadina
2014-08-08,Friday,"25°C, no rain",17,9,6,2,4,3,6,18,...,81,84,72,45,30,26,29,1227,EB,Adelaide and Spadina
2014-08-09,Saturday,"26°C, no rain",18,13,8,8,5,3,5,16,...,98,66,68,39,38,25,21,1181,EB,Adelaide and Spadina
2015-07-17,Friday,"21°C, 5mm rain",1,0,0,0,0,1,3,6,...,8,6,6,1,1,2,0,60,EB,Eglinton and Eden Valley
2015-07-17,Friday,"21°C, 5mm rain",1,0,0,0,0,0,5,10,...,0,3,2,1,4,0,1,40,WB,Eglinton and Eden Valley
2015-07-17,Friday,"21°C, 5mm rain",2,0,0,0,0,1,8,16,...,8,9,8,2,5,2,1,100,Total,Eglinton and Eden Valley
2015-07-18,Saturday,"29°C, no rain",0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,14,EB,Eglinton and Eden Valley
2015-07-18,Saturday,"29°C, no rain",0,0,0,0,0,0,0,0,...,2,2,0,0,1,0,0,14,WB,Eglinton and Eden Valley
2015-07-18,Saturday,"29°C, no rain",0,0,0,0,0,0,0,0,...,2,2,0,0,2,0,0,28,Total,Eglinton and Eden Valley
2015-07-19,Sunday,"30°C, no rain",0,0,0,0,0,0,0,1,...,1,5,1,4,1,1,0,44,EB,Eglinton and Eden Valley
2015-07-19,Sunday,"30°C, no rain",0,1,0,0,0,0,0,0,...,3,3,1,3,0,2,0,32,WB,Eglinton and Eden Valley
2015-07-19,Sunday,"30°C, no rain",0,1,0,0,0,0,0,1,...,4,8,2,7,1,3,0,76,Total,Eglinton and Eden Valley
2015-07-20,Monday,"28°C, no rain",0,0,0,0,0,0,3,4,...,26,26,25,11,10,0,2,137,EB,Eglinton and Eden Valley
2015-07-20,Monday,"28°C, no rain",0,0,0,0,0,0,3,6,...,11,13,4,13,2,2,1,80,WB,Eglinton and Eden Valley
2015-07-20,Monday,"28°C, no rain",0,0,0,0,0,0,6,10,...,37,39,29,24,12,2,3,217,Total,Eglinton and Eden Valley
2015-07-21,Tuesday,"27°C, no rain",1,0,0,0,0,0,6,5,...,29,29,17,36,12,1,0,228,EB,Eglinton and Eden Valley
2015-07-21,Tuesday,"27°C, no rain",0,0,0,0,0,1,11,17,...,17,10,11,23,5,1,3,169,WB,Eglinton and Eden Valley
2015-07-21,Tuesday,"27°C, no rain",1,0,0,0,0,1,17,22,...,46,39,28,59,17,2,3,397,Total,Eglinton and Eden Valley
2015-07-22,Wednesday,"26°C, no rain",1,0,1,0,0,0,6,7,...,35,27,10,13,4,2,1,182,EB,Eglinton and Eden Valley
2015-07-22,Wednesday,"26°C, no rain",1,0,0,0,0,1,7,21,...,10,10,7,7,4,0,1,135,WB,Eglinton and Eden Valley
2015-07-22,Wednesday,"26°C, no rain",2,0,1,0,0,1,13,28,...,45,37,17,20,8,2,2,317,Total,Eglinton and Eden Valley
2015-07-23,Thursday,"27°C, no rain",2,1,1,0,0,1,5,8,...,25,27,24,16,2,3,0,198,EB,Eglinton and Eden Valley
2015-07-23,Thursday,"27°C, no rain",1,0,0,0,1,2,7,28,...,15,4,12,11,9,6,2,162,WB,Eglinton and Eden Valley
2015-07-23,Thursday,"27°C, no rain",3,1,1,0,1,3,12,36,...,40,31,36,27,11,9,2,360,Total,Eglinton and Eden Valley
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-06-01,Monday,"15°C, no rain",1,1,1,0,0,0,7,31,...,143,79,52,37,28,13,7,775,NB,Simcoe and Adelaide
2015-06-01,Monday,"15°C, no rain",1,1,0,0,1,2,24,64,...,65,48,33,19,8,11,9,799,SB,Simcoe and Adelaide
2015-06-01,Monday,"15°C, no rain",2,2,1,0,1,2,31,95,...,208,127,85,56,36,24,16,1574,Total,Simcoe and Adelaide
2015-06-02,Tuesday,"18°C, no rain",7,4,0,3,0,4,12,59,...,164,128,54,52,35,26,26,1040,NB,Simcoe and Adelaide
2015-06-02,Tuesday,"18°C, no rain",6,1,2,1,1,3,24,87,...,87,57,35,21,24,13,5,1049,SB,Simcoe and Adelaide
2015-06-02,Tuesday,"18°C, no rain",13,5,2,4,1,7,36,146,...,251,185,89,73,59,39,31,2089,Total,Simcoe and Adelaide
2015-06-03,Wednesday,"18°C, no rain",7,3,3,2,0,3,8,38,...,186,109,39,53,47,34,23,1058,NB,Simcoe and Adelaide
2015-06-03,Wednesday,"18°C, no rain",8,2,1,0,1,3,29,86,...,85,57,46,30,19,13,3,1115,SB,Simcoe and Adelaide
2015-06-03,Wednesday,"18°C, no rain",15,5,4,2,1,6,37,124,...,271,166,85,83,66,47,26,2173,Total,Simcoe and Adelaide
2015-06-04,Thursday,"22°C, no rain",12,7,5,4,1,1,16,42,...,183,91,60,36,22,24,28,1017,NB,Simcoe and Adelaide
2015-06-04,Thursday,"22°C, no rain",0,2,0,1,3,7,29,90,...,80,62,42,23,17,20,8,1104,SB,Simcoe and Adelaide
2015-06-04,Thursday,"22°C, no rain",12,9,5,5,4,8,45,132,...,263,153,102,59,39,44,36,2121,Total,Simcoe and Adelaide
2015-06-17,Wednesday,"21°C, no rain",14,5,3,0,1,2,8,22,...,137,100,44,41,36,35,20,803,EB,Wellesley and Parliament
2015-06-17,Wednesday,"21°C, no rain",5,3,0,1,1,4,15,44,...,41,44,31,32,13,13,9,639,WB,Wellesley and Parliament
2015-06-18,Thursday,"26°C, no rain",9,6,2,1,3,6,6,17,...,97,83,56,38,31,28,12,745,EB,Wellesley and Parliament
2015-06-18,Thursday,"26°C, no rain",6,6,0,0,3,3,11,28,...,28,46,30,36,33,13,8,598,WB,Wellesley and Parliament
2015-06-19,Friday,"20°C, no rain",11,8,1,4,2,2,6,12,...,128,67,48,28,25,30,29,768,EB,Wellesley and Parliament
2015-06-19,Friday,"20°C, no rain",4,2,0,0,2,2,21,27,...,42,31,44,18,23,22,14,652,WB,Wellesley and Parliament
2015-06-20,Saturday,"22°C, no rain",16,10,3,2,1,5,5,12,...,38,52,38,21,30,27,12,609,EB,Wellesley and Parliament
2015-06-20,Saturday,"22°C, no rain",13,8,2,4,1,0,2,5,...,42,37,26,29,15,9,19,506,WB,Wellesley and Parliament
2015-06-21,Sunday,"28°C, no rain",23,17,11,3,1,7,1,11,...,37,29,33,25,24,14,13,520,EB,Wellesley and Parliament
2015-06-21,Sunday,"28°C, no rain",8,11,1,2,4,3,1,7,...,40,33,20,20,22,19,8,429,WB,Wellesley and Parliament
2015-06-22,Monday,"27°C, 21mm rain",9,4,7,8,0,2,5,18,...,146,85,64,34,21,20,8,720,EB,Wellesley and Parliament
2015-06-22,Monday,"27°C, 21mm rain",4,3,1,1,1,4,18,29,...,46,36,31,21,13,15,3,554,WB,Wellesley and Parliament
2015-06-23,Tuesday,"27°C, 1mm rain",4,3,0,1,0,2,3,15,...,106,88,52,42,40,22,19,713,EB,Wellesley and Parliament
2015-06-23,Tuesday,"27°C, 1mm rain",2,2,2,2,1,4,17,20,...,44,39,34,36,21,13,11,612,WB,Wellesley and Parliament
2015-06-24,Wednesday,"25°C, no rain",7,5,2,2,1,2,6,22,...,120,128,66,38,35,27,22,841,EB,Wellesley and Parliament
2015-06-24,Wednesday,"25°C, no rain",7,2,0,0,1,2,20,24,...,46,48,35,26,25,14,15,708,WB,Wellesley and Parliament
2015-06-25,Thursday,"23°C, no rain",7,6,3,3,2,4,10,18,...,107,86,52,38,27,21,21,707,EB,Wellesley and Parliament
2015-06-25,Thursday,"23°C, no rain",2,3,0,3,4,5,18,31,...,28,24,30,23,24,17,8,562,WB,Wellesley and Parliament